### PR TITLE
Change repo name to standard GitHub pages name

### LINKED ISSUE #161: Change repo name to standard GitHub pages name
Currently the website URL has the repo name website as the leading element. If we [want to get rid of this](https://stackoverflow.com/questions/44531269/is-there-a-way-to-remove-repository-name-from-github-page-link) we need to [change the name](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site) of the repo to [access-hive.github.io](http://access-hive.github.io/)

### PR DESCRIPTION
**Pull request by aidanheerdegen**
# ACCESS Community Hive 

Thank you for submitting a pull request to the ACCESS Hive Project. 

## Description

Please include a brief summary of the change and list the issues that are fixed.
Please also include relevant motivation and context.

You can link issues by using a supported keyword in the pull request's description or in a commit message:

Fixes #161

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue, e.g. dead links)
- [ ] New link / content

## Checklist:

- [x] The new content is accessible and located in the appropriate section.
- [x] My changes do not break navigation and do not generate new warnings
- [x] I have checked that the links are valid and point to the intended content.
- [x] I have checked my code/text and corrected any misspellings

Please tag the **reviewers team** in a comment below by prepending an `@` in front of `ACCESS-Hive/reviewers` when ready.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Oh. That has broken the Preview action URL. Should no longer have the repo name in it, and instead just be

https://access-hive.github.io/pr-preview/pr-162

which works.

**Comment by aidanheerdegen** [comment]
Submitted an issue https://github.com/rossjrw/pr-preview-action/issues/22

**Comment by ccarouge** [comment]
It seems rossjrw has finally updated the pr-preview-action. From a first look, it seems we can use his directly and remove our fork! I'll test it to make sure. I might ask you @aidanheerdegen for a test commit once ready.

**Comment by aidanheerdegen** [comment]
I think we should merge this after review, and fix the preview separately

Ready for review @ACCESS-Hive/reviewers

**Review by rbeucher — APPROVED** [review]
Looks good to me. 
I just fixed the `git clone` command

**Comment by aidanheerdegen** [comment]
Thanks

**Pull request merged**
