### PR TITLE
Add Bureau R&D workshop

### PR DESCRIPTION
**Pull request by aidanheerdegen**
# ACCESS Community Hive 

Thank you for submitting a pull request to the ACCESS Hive Project. 

## Description

Please include a brief summary of the change and list the issues that are fixed.
Please also include relevant motivation and context.

You can link issues by using a supported keyword in the pull request's description or in a commit message:

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue, e.g. dead links)
- [x] New link / content

## Checklist:

- [x] The new content is accessible and located in the appropriate section.
- [x] My changes do not break navigation and do not generate new warnings
- [x] I have checked that the links are valid and point to the intended content.
- [x] I have checked my code/text and corrected any misspellings

Please tag the **reviewers team** in a comment below by prepending an `@` in front of `ACCESS-Hive/reviewers` when ready.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Hey @ACCESS-Hive/reviewers this is ready for review.

I was interested in trying to add an event entirely through the GitHub web interface. Worked ok. I can document that method if that is useful.

**Review by rogeredberg — APPROVED** [review]
Looks good

**Comment by dougiesquire** [comment]
Out of interest, why can't I see the event on the PR Preview link above? I'm sure I'm doing something stupid

**Comment by rbeucher** [comment]
No the PR Preview is broken

**Comment by rbeucher** [comment]
The file extension was missing.That's one problem solve.
Also, the title needed to be put in quotes... the semi-column was creating issues while parsing the metadata.

@aidanheerdegen  is fixing the preview link which currently redirects to the website (not the preview)

**Review by rbeucher — APPROVED** [review]

**Pull request merged**
