### PR TITLE
ACCESS-Hive responsive

### LINKED ISSUE #510: Make Hive responsive for use on different devices
## Description
Make all parts (Header, main body, footer, etc..) of the website responsive so that they are rendered well on multiple devices (diffrent screen size) --> PC/Laptops, Tablets, Phones

## Why
With many people using tablet and phones to browse the web, is important to give everyone a good user experience

## Close Criteria
Website is well rendered (and tested) for all types of devices.

### PR DESCRIPTION
**Pull request by atteggiani**
Fixes #510 

Hive is fully responsive.

### CODE REVIEW

**Comment by svenbuder** [comment]
- [ ] Adjust fontsize for terminal animations

**Comment by svenbuder** [comment]
- [ ] try to optimise navigation through the sections via top left buttons (if possible)

As we discussed, the way to navigate the mobile version with clicking on "Home" before you see the lower levels is not intuitive. We can do a bit more research on this, but it might just be the way that mkdocs/materials works...

**Comment by svenbuder** [comment]
Everything else looks great!

**Comment by atteggiani** [comment]
- [x] Changed font-size of animated terminal windows to be same as `<code>` tag;
- [x] Prevent navigation pad to show when using burger menu if the current page has no subpages (e.g. home).

**Pull request merged**
