### PR TITLE
Create WCRP Conference

### PR DESCRIPTION
**Pull request by NBateman-bit**
# ACCESS Community Hive 

Thank you for submitting a pull request to the ACCESS Hive Project. 🎉

## Description

Adds the WCRP event to the events tab

Now, if you really wanna make the ACCESS-Hive developers life easier, then consider filling up what follows. 😍
If you find this intimidating or you don't really know what some of those bullet points mean, then just delete everything from here onwards. 🫣

## Type of change

- [x] New link / content

## Checklist:

- [x] The new content is accessible and located in the appropriate section.
- [x] My changes do not break navigation and do not generate new warnings
- [x] I have checked that the links are valid and point to the intended content.
- [x] I have checked my code/text and corrected any misspellings
- [ ] I have chosen the correct tag for the level of [support provided](https://access-hive.org.au/#support).

Please tag the **reviewers team** in a comment below by prepending an `@` in front of `ACCESS-Hive/reviewers` when ready.

### CODE REVIEW

**Comment by NBateman-bit** [comment]
@ACCESS-Hive/reviewers

**Comment by aidanheerdegen** [comment]
Hey Natalia. Thanks for submitting this. 

The file you upload should have a suffix of `.md`. It is also best not to have spaces in file names. Usual convention is to use an underscore `_` where a space might be used otherwise.

I can fix this, or leave it up to you.

**Comment by rbeucher** [comment]
Yes. My plugin requires the `.md` extension.
I should add a warning when it finds file without the extension. It is currently silent...

**Comment by rbeucher** [comment]
All good

**Pull request merged**
