### PR TITLE
Aidanheerdegen/issue215

### LINKED ISSUE #215: How can users get support from ACCESS-NRI?
Should the ACCESS-Hive include some info on how simple users can get help?

This: https://access-hive.org.au/about/support/ just mentions to contact ACCESS-NRI directly.

Perhaps point users to the forum and urge them to search through there to see if what they are struggling with has been discussed before or open a new discussion if not?

### LINKED ISSUE #225: Clarify instructions to add events
For newcomers to GitHub, it can be confusing to know what are all the steps needed when adding an event. 

The [Add event](https://access-hive.org.au/events/add_event/) page explains how to create the file but does not say where (in a branch) and does not explain the pull request process.

### PR DESCRIPTION
**Pull request by aidanheerdegen**
## Description

Added paragraph to support page pointing to forum.
Added forum links to contact page.
Updated the add event page with information about new form template as minimum required to add event: makes for a lower barrier for event submission.

Fixes #225
Fixes #215

(Delete the instructions after you write your description. 🙃)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue, e.g. dead links)
- [x] New link / content

## Checklist:

- [x] The new content is accessible and located in the appropriate section.
- [x] My changes do not break navigation and do not generate new warnings
- [x] I have checked that the links are valid and point to the intended content.
- [x] I have checked my code/text and corrected any misspellings
- [ ] I have chosen the correct tag for the level of [support provided](https://access-hive.org.au/#support).

Please tag the **reviewers team** in a comment below by prepending an `@` in front of `ACCESS-Hive/reviewers` when ready.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
@rbeucher I don't know why, but I didn't put fields in the template for organisers and comments. Maybe the file I was basing it off didn't have those fields? Or I was just looking at the rendered versions in the web page? In any case, those fields aren't used it seems. Do we want to make sure they are included, so I should add them to the form? If not they should be removed form the example.

**Comment by rbeucher** [comment]
I don't think they are used. I put together the plugin together quite quickly thinking we would decide what we want to capture later on...

**Comment by aidanheerdegen** [comment]
So is it ok to leave those fields out of the template, and remove them from the example? Or do you envisage needing that data in the future?

**Comment by rbeucher** [comment]
I would keep them. That does not hurt right?

**Comment by rbeucher** [comment]
I would keep them. That does not hurt right?

**Comment by aidanheerdegen** [comment]
No, but it puts an extra burden on contributors for fields we do not currently use. My preference would be to get rid of them unless there are immediate plans to use them.

**Review by rbeucher — CHANGES_REQUESTED** [review]
Shall we clean the metadata for the existing events?

**Comment by aidanheerdegen** [comment]
> Shall we clean the metadata for the existing events?

Nah, it is basically invisible so fine to leave as-is.

**Comment by aidanheerdegen** [comment]
@rbeucher waiting on your ok

**Review by rbeucher — APPROVED** [review]

**Comment by rbeucher** [comment]
OK

**Pull request merged**
