### PR TITLE
Update ESMValTool instructions on Gadi

### PR DESCRIPTION
**Pull request by rbeucher**
Update the instructions on how to load/use ESMValTool on Gadi.

### CODE REVIEW

**Review by flicj191 — APPROVED** [review]

**Comment by rbeucher** [comment]
@atteggiani  Things like that should go to `main` directly. We want the users to have access to the latest information...

**Comment by atteggiani** [comment]
> @atteggiani Things like that should go to `main` directly. We want the users to have access to the latest information...

@rbeucher I disagree. 
I agree that users should have access to the latest information, but if we have a general workflow that creates PRs with `development` and then periodically merges it to `main` I would still follow it. 
In this case, if we think it's something that should be merged more quickly, I would still create a PR to `development`, and then once it's merged I would merge development into `main`.

**Comment by rbeucher** [comment]
Dev should be for new functionalities, not content... 
We are releasing ESMValTool at the end of the week. I am gonna have to make some changes.
If you merge dev into main you take the risk of breaking things... We need a bit more flexibility here.

**Comment by atteggiani** [comment]
But many of our new development will only be content. I still think we should be following the standard workflow for that.

We should not be breaking anything by merging Development to Main. 
That's because we should check every PR to Development (1st check) and then double check when we merge to main. 
Of course there is always the possibility to overlook some things, but in general I think this is a good methodology/workflow to keep mistakes to a minimum. 

Anyway, we can discuss this better tomorrow during the Hive docs meeting (1:30pm). 
I can let you know in case you want to join only when we talk about this.

**Pull request merged**
