### PR TITLE
Edited text in bgc_ocean.md

### PR DESCRIPTION
**Pull request by heidinett**
Edited text in the bgc_ocean.md of Model Components on the ACCESS-Hive.

@matt-csiro - Are there any other more-relevant links for WOMBAT?

Fixes Issue #379

### CODE REVIEW

**Comment by KAUR1984** [comment]
Can be closed once merged.

**Review by matt-csiro — COMMENTED** [review]
IMO, the description of NPZD fits better in the "WOMBAT" section, and please mention CSIRO here, I suggest the following modifications: 

"The World Ocean Model of Biogeochemistry And Trophic-dynamics (WOMBAT) is the ocean biogeochemistry module added to ACCESS models.  The core of WOMBAT is a Nutrient, Phytoplankton, Zooplankton and Detritus (NPZD) cycle. WOMBAT simulates the evolution of open-ocean phosphate, oxygen, dissolved inorganic carbon, alkalinity, iron and carbon fluxes with one zooplankton and one phytoplankton class."  

Under "How is WOMBAT used?"...
Yes, "WOMBAT is applied as a tracer package in MOM5." (shift reference to NPZD to previous section)
There are two implementations that could be referred to here for clarity.
Perhaps, 
"WOMBAT in [link to COSIMA MOM5 repository, https://github.com/mom-ocean/MOM5] is used in ACCESS-OM2, coupled with sea ice BGC, and, 
WOMBAT in [link to https://github.com/COSIMA/ACCESS-ESM1.5-MOM5] is used for ACCESS-ESM1.5 for CMIP6."

Hope this helps,
Cheers, Matt.

**Comment by heidinett** [comment]
Thanks @matt-csiro  for your feedback and suggestions! I have incorporated these into the text. 
Could you please check what I wrote is correct.

Cheers,
Heidi

**Review by KAUR1984 — APPROVED** [review]
Looks good to me. Thanks for the changes @heidinett !

**Pull request merged**
