### PR TITLE
Use icons with text on top for the model components

### LINKED ISSUE #223: Change icons in Model components table
We need to use the new icons in the model components table with the names of the components at the top of the icon.

### PR DESCRIPTION
**Pull request by ccarouge**
# ACCESS Community Hive 

Thank you for submitting a pull request to the ACCESS Hive Project. 🎉

## Description

Change icons in the table on the home page of the model components so the text is always at the top
Change icons on each model component page.

Fixes #223

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue, e.g. dead links)

## Checklist:

- [ ] My changes do not break navigation and do not generate new warnings
- [ ] I have checked that the links are valid and point to the intended content.
- [ ] I have checked my code/text and corrected any misspellings

Please tag the **reviewers team** in a comment below by prepending an `@` in front of `ACCESS-Hive/reviewers` when ready.

### CODE REVIEW

**Comment by ccarouge** [comment]
@ACCESS-Hive/reviewers ready

**Review by navidcy — APPROVED** [review]
nice, looks nice...

what was the issue before? perhaps I missed checking that?

**Comment by rbeucher** [comment]
I wasn't sure about this. I think it looks a bit too heavy.... 
Personal taste I suppose. That does simplify things though as we only have one icon per domain.

**Comment by ccarouge** [comment]
@navidcy the previous version of the icons has the text either at the top or at the bottom. For example in the table on the same row we had atm and land written above the icon and switching to text below for ocean and sea-ice. You can still see it on the published site: https://access-hive.org.au/model_components/ 

@rbeucher Actually, the same icons were already used in the table in the index and on each component page, so I didn't think it was worth doubling the set.

**Comment by rbeucher** [comment]
Yes I understand. That's what I meant when I wrote that it simplifies things. We don't need the logos without text if we do that.

**Comment by navidcy** [comment]
ok, it boils down to a matter of aesthetics

I guess text being both top or bottom was trying to allegorize the fact that ocean is below the atmosphere...

**Comment by ccarouge** [comment]
@rbeucher Use the dark mode, and then the text disappears... sigh...

**Comment by navidcy** [comment]
usual problems of web developers

**Comment by aidanheerdegen** [comment]
> usual problems of web developers

True dat

**Pull request merged**
