### PR TITLE
Update nav.html

### LINKED ISSUE #210: Rename `ACCESS-Forum` to `ACCESS-Hive Forum`?
I know that it may be too long name? But already some people are a bit confused with "ACCESS-Hive" and "ACCESS-Hive Forum" so if you add another extra name "ACCESS-Forum" they might think it's a new thing... (I know I thought of that myself!)

https://github.com/ACCESS-Hive/access-hive.github.io/blob/e9394401e7e7f4219bb3983fb3ac8dbf12418915/overrides/partials/nav.html#L80

### PR DESCRIPTION
**Pull request by navidcy**
# ACCESS Community Hive 

Thank you for submitting a pull request to the ACCESS Hive Project. 

## Description

Rename "ACCESS-Forum" to "ACCESS-Hive Forum"

Closes #210

## Checklist:

- [x] The new content is accessible and located in the appropriate section.
- [x] My changes do not break navigation and do not generate new warnings
- [x] I have checked that the links are valid and point to the intended content.
- [x] I have checked my code/text and corrected any misspellings
- [x] I have chosen the correct tag for the level of [support provided](https://access-hive.org.au/#support).

Please tag the **reviewers team** in a comment below by prepending an `@` in front of `ACCESS-Hive/reviewers` when ready.

### CODE REVIEW

**Review by dougiesquire — APPROVED** [review]

**Review by rbeucher — APPROVED** [review]

**Comment by aidanheerdegen** [comment]
FYI

> MOM5 is open source and is the current version of MOM used within ACCESS is MOM5.

Doesn't really make sense.

**Comment by aidanheerdegen** [comment]
Yes, too many PR tabs open. Thanks @dougiesquire

**Comment by rbeucher** [comment]
I have created a new one. hhahhha

**Comment by rbeucher** [comment]
I'm OK with targeted PRs.

**Pull request merged**
