### PR TITLE
Davide/colorscheme

### LINKED ISSUE #484: HIVE COLOR SCHEME: Change the color scheme of light and dark mode (as per feedback from the skillshare)
## Description
@atteggiani

### PR DESCRIPTION
**Pull request by atteggiani**
Fixes #484 
- [x] Fixed colorscheme as requested in Skillshare meeting.
- [x] Removed highlighted background from page titles
- [x] Restructured a few classes

### CODE REVIEW

**Review by KAUR1984 — CHANGES_REQUESTED** [review]
Thanks so much for your changes @atteggiani ! 

- Removing the highlighted backgrounds from headings is looking really good to me. 
- Just a comment on the navigation bar at the top, I am not really sure about having a gold line at the bottom of this bar - would this be something we could discuss in the coming sprint meeting on Friday? 

Overall, other than these minor suggestions for color scheme (which we could always discuss collectively), I am very happy with the changes made :)

**Comment by atteggiani** [comment]
> * Just a comment on the navigation bar at the top, I am not really sure about having a gold line at the bottom of this bar - would this be something we could discuss in the coming sprint meeting on Friday?

Yeah totally! 
It was an idea initially raised by Harshula, and I thought it looked nice so I implemented it. 
But happy to discuss it also in today's meeting (it will take 3 minutes to decide, and 30 secs to remove it in case) :)

**Comment by atteggiani** [comment]
@KAUR1984 
Removed the yellow line as decided in the meeting.
If you are ok with it I will merge (or you can merge it yourself).

**Comment by KAUR1984** [comment]
Looks good to me! Thanks @atteggiani !

**Review by KAUR1984 — APPROVED** [review]

**Pull request merged**
