### PR TITLE
Review of "how to contribute" guide

### PR DESCRIPTION
**Pull request by ccarouge**
# ACCESS Community Hive 

Thank you for submitting a pull request to the ACCESS Hive Project. 

## Description

Please include a brief summary of the change and list the issues that are fixed.
Please also include relevant motivation and context.

You can link issues by using a supported keyword in the pull request's description or in a commit message:

Fixes # 133

I have modified the contribution guide in several ways:

 - moved from 1 page to several pages. All under a "How to contribute" section in the "About" tab.
 - added information about standalone documentation (ie. not available via a website).
 - link to the forum to become a member of ACCESS-Hive organisation. Needs to be updated to point to a specific thread when it exists.
 - when editting from GitHub, added instructions for further edits (e.g. requests from review)
 - moved the installation and preview instructions to the page to edit locally as that is where it is pertinent.

## Type of change

Please delete options that are not relevant.

- [X] New link / content

## Checklist:

- [X] The new content is accessible and located in the appropriate section.
- [X] My changes do not break navigation and do not generate new warnings
- [X] I have checked that the links are valid and point to the intended content.
- [X] I have checked my code/text and corrected any misspellings

Please tag the **reviewers team** in a comment below by prepending an `@` in front of `ACCESS-Hive/reviewers` when ready.

### CODE REVIEW

**Comment by ccarouge** [comment]
@ACCESS-Hive/reviewers

**Comment by ccarouge** [comment]
This is not ready finally. Need to remove conda as an option for installation. mkdocs does not maintain their `conda-forge` package up to date.

**Comment by rbeucher** [comment]
@ccarouge can I merge this or are you still working on it?

**Comment by ccarouge** [comment]
Thanks for the work. It should be ready.

**Review by rbeucher — APPROVED** [review]

**Pull request merged**
