### PR TITLE
Edited text in coupler.md 

### PR DESCRIPTION
**Pull request by heidinett**
Edited text in coupler.md of Model Components.

Fixes Issue #380

### CODE REVIEW

**Comment by KAUR1984** [comment]
Can be closed once merged.

**Comment by MartinDix** [comment]
I'd say a software package rather than a software.

Some sort of formatting error under OASIS3-MCT because models are appearing as - ACCESS-ESM1.5 - ACCESS-CM2 - ACCESS-OM2 - ACCESS-S rather than as dot points as before.

With ACCESS-OM3,add a link to the coupler choices discussion at https://github.com/COSIMA/access-om3/discussions/7

**Comment by heidinett** [comment]
Thanks Martin for your comments. I have made the proposed changes.

**Comment by MartinDix** [comment]
Looks good.

**Pull request merged**
