### PR TITLE
Try mailto link to join organisation

### PR DESCRIPTION
**Pull request by rbeucher**
I just thought about this to lower the barrier of joining the organisation...

Let me know what you think

### CODE REVIEW

**Comment by rbeucher** [comment]
@ccarouge @aidanheerdegen What do you think?

**Comment by ccarouge** [comment]
I've clicked the button but I have no idea if that worked or not. This is a recipe to get 10 emails in a row from people clicking repeatedly to see if it works...

I thought we didn't want to use personal emails because then it puts too much burden on one person. Also, we said there would be some screening of who would join the organisation. That was a condition to give write permissions to members. This means, you receive an email, then write back an email (do you have an email address to write back to?) to ask who they are and their link with ACCESS, receive the reply and then discuss with others to know if that's ok. Or am I making the screening requirement too complicated?

**Comment by aidanheerdegen** [comment]
I clicked the button and got an email pre-filled. Is that not what you got @ccarouge?

There are ways to add users programmatically 

https://github.com/benbalter/add-to-org

https://medium.com/code-applied-to-life/automated-github-organization-invites-3e940aa27040

It might work to allow automatic sign up from trusted email domains, but that would require verifying the email address matched, and then emailing them a link which included a time limited token. Something like auth0 might work for that, but quite complex to set up

https://auth0.com/docs/manage-users/user-accounts/verify-emails#magic-link-in-a-verification-email

and requires a persistent sign-up server.

**Comment by aidanheerdegen** [comment]
We could have an open issue for sign-up and ask people to ping a team to ask to become a member?

**Comment by ccarouge** [comment]
@rbeucher What is wrong with pointing them to the discussion page with the maintainers team: https://github.com/orgs/ACCESS-Hive/teams/maintainers?

**Comment by aidanheerdegen** [comment]
Can non-maintainers see that discussion page?

**Comment by rbeucher** [comment]
It's the pre-fill email that I thought would be useful. 
Using my email was just a test.

**Comment by rbeucher** [comment]
> @rbeucher What is wrong with pointing them to the discussion page with the maintainers team: https://github.com/orgs/ACCESS-Hive/teams/maintainers?

I don't think that works if you are not part of the organisation...

**Comment by ccarouge** [comment]
> Can non-maintainers see that discussion page?

Non-maintainers yes, but probably not non-members of the organisation which defeats the purpose

**Comment by ccarouge** [comment]
> Using my email was just a test.

What email would we use?

**Comment by aidanheerdegen** [comment]
Have we reached any consensus? Is there any problem with leaving the pinned issue there even if we also have other ways to reach folks?

If there is no problem with keeping the sign-up issue, I'd prefer to delete the comments in the issue as they're somewhat distracting.

**Comment by rbeucher** [comment]
No consensus I think... We don't have a much better solution than the issue I think...

**Comment by rbeucher** [comment]
Let's close this for now...

**Pull request closed without merging**
