### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rbeucher**
Fix Issue raised in #211

### CODE REVIEW

**Review by navidcy — APPROVED** [review]
sorry

**Comment by navidcy** [comment]
Why `Check Markdown links` fails?

**Comment by dougiesquire** [comment]
@navidcy, one of the external links we point to (the [FREVA](https://freva.gitlab-pages.dkrz.de/evaluation_system/sphinx_docs/index.html) website) is currently down. Links will go down periodically, so we'll only worry about removing broken links if they start to become a persistent issue.

**Comment by navidcy** [comment]
oh I *now* can see [https://github.com/ACCESS-Hive/access-hive.github.io/actions/runs/3457263201/jobs/5770572342#step:4:432]

I was skimming the log and was seeing everything passing.

Thanks @dougiesquire

**Pull request merged**
