### PR TITLE
Move landing page to its own category

### LINKED ISSUE #260: Confusing UI on my phone
I'm possibly (probably) being dumb, but navigating to different pages (Configurations, Training etc) on the ACCESS Hive website feels a little unintuitive. After first arriving at the website, I have to click the menu icon and then click "<-" in the sidebar in order to see the available pages

then

### PR DESCRIPTION
**Pull request by ccarouge**
# ACCESS Community Hive 

Thank you for submitting a pull request to the ACCESS Hive Project. 🎉

More assistance is available in the [how to contribute section on ACCESS-Hive](https://access-hive.org.au/about/contribute/)

## Description

The mobile UI has an unintuitive nagivation. This is solved by moving the landing page to a "Home" tab on its own.

The ticket:
 - creates the Home tab for the landing page
 - reorganises the About tab to land on the Contact page in this tab
 - moves the About tab to the end of the tab bar
 - removes a redundant heading in the Contact page

Fixes #260

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue, e.g. dead links)

## Checklist:

- [X] The new content is accessible and located in the appropriate section
- [X] My changes do not break navigation and do not generate new warnings
- [X] I have checked that the links are valid and point to the intended content
- [X] I have checked my code/text and corrected any misspellings

When your pull request is ready please [request a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review). 

Unless there is a specific person you want to review your PR please select the **reviewers team**: `ACCESS-Hive/reviewers`. This ensures the load for reviewing pull requests is shared equitably.

### CODE REVIEW

**Comment by ccarouge** [comment]
This is not enough. When opening the menu, we are in the "Home" tab with an empty navigation. So we still need to go one level up to see the "tabs".

**Comment by ccarouge** [comment]
@dougiesquire This seems to work on my mobile. Can you go to the preview landing page on your mobile and check as well?

**Review by dougiesquire — APPROVED** [review]
Yes - this works great! Thanks @ccarouge

**Comment by ccarouge** [comment]
@rbeucher @aidanheerdegen @dougiesquire The navigation on mobile is fixed except that messes up the About tab.

I propose to do the following:

1. Change the order of pages/sections so we land on the contact page:

    - Contact
    - Support
    - Code of conduct
    - How to contribute 
    - License

2. Move the "About" tab to the end of the tab bar (last tab).
3. Bonus: I propose to remove the first level 2 heading on the contact page which is redundant with the page title.
```
# Contact
## Who to contact about ACCESS-Hive? 
```
Any better idea?

**Comment by rbeucher** [comment]
Go for it. Looks good to me

**Pull request merged**
