### PR TITLE
Added to Resources: Aus Reference Climate Data Collection

### PR DESCRIPTION
**Pull request by heidinett**
Added Australian Community Reference Climate Data Collection @ NCI to "Resources" section, which also includes an intake-esm catalogue.

### CODE REVIEW

**Comment by rbeucher** [comment]
@ACCESS-Hive/reviewers

**Comment by aidanheerdegen** [comment]
@rbeucher We are thinking we should move *all* the data catalogue stuff under Resources > Data. Maybe the data processing stuff too. I don't know if that means we should rename the tab simply "Model Evaluation"?

**Review by heidinett — COMMENTED** [review]
Issue 3207: Created a Tools section under "Resources" tab that collates an index of useful tools

**Comment by rbeucher** [comment]
What does "ressources" mean in the context of the Hive which is already a collection of ressources?
Also, does this PR assumes that the PR #252 Is being merged? That's confusing.

**Comment by rbeucher** [comment]
Can you move this to Data catalogues @heidinett ?

**Comment by heidinett** [comment]
> Can you move this to Data catalogues @heidinett ?

Sure. Just to clarify, you would prefer that is goes in: Model Evaluation & Data -> Data Catalogs and then under "NCI datasets" or as a separate entry here?

**Comment by rbeucher** [comment]
I think a separate entry is fine...

**Review by rbeucher — APPROVED** [review]

**Pull request merged**
