### PR TITLE
Added CMIP6 and ERA5 Variable Tables

### PR DESCRIPTION
**Pull request by svenbuder**
@rbeucher : Can you advise on the following:

for ERA5, do we only want the netCDF conform variables, or all (I can easily include all and add a column "netCDF?").

This is the first PR in addressing #292

### CODE REVIEW

**Comment by rbeucher** [comment]
We should have all. I think.

**Comment by rbeucher** [comment]
The search functionality does not work for me... does the plugin need to be deployed on the main site?

**Comment by svenbuder** [comment]
> The search functionality does not work for me... does the plugin need to be deployed on the main site?

It seems to be very slow on the PR-preview. The CMIP6 takes ~2 seconds to react and ERA5 is quicker. It works instantly on my computer though...

**Comment by svenbuder** [comment]
> We should have all. I think.

Good. Will adjust.

**Comment by KAUR1984** [comment]
Will close it once merged.

**Comment by svenbuder** [comment]
Decided to not implement these changes for the Legacy Release. Closing this Pull Request.

**Pull request closed without merging**
