### PR TITLE
310 write content for how to run access om

### PR DESCRIPTION
**Pull request by atteggiani**
- [x] Wrote content on how to run ACCESS-OM ("output" paragraph still to revise)
- [x] Some improvements to all "how to run ..." pages 
- [x] Restructured "fontello" and "fontawesome" icons folders. It doesn't change anything in the markdown files/codes, but now all respective files are kept in the respective folders `docs/fontello` and `docs/fontawesome-free-6.4.0-web` while changing the `mkdocs.yaml` file to load css files needed for the icons. This keeps the `docs/css` folder cleaner and makes it easier to add new "fontello" icons to the available icons pack.
This is the reason why you see so many files changed (that's mostly the files inside `fontawesome-free-6.4.0-web` that got moved).
- [x] Added icons for external links

### CODE REVIEW

**Comment by atteggiani** [comment]
@KAUR1984 @svenbuder 
Can you please check if you like the rendering of external link icons? 

A part of me likes them, but a part of me thinks there is something that might be improved. 
Thank you!

**Comment by KAUR1984** [comment]
Thanks for these changes @atteggiani ! These icons are already looking great to me and are really informative overall on the hive for showing external websites links. 

Just a thought on the `vertical alignment` of the icon - do these icons look better if aligned at the top (as in the current implementation) or could we possibly try vertically centering them? 

Otherwise, I am very happy with the current implementation :)

**Comment by KAUR1984** [comment]
Whoops, I think we got some conflicts with the changes made in the latest pr - https://github.com/ACCESS-Hive/access-hive.github.io/pull/443#event-9832597525.

**Comment by atteggiani** [comment]
> Whoops, I think we got some conflicts with the changes made in the latest pr - [#443 (comment)](https://github.com/ACCESS-Hive/access-hive.github.io/pull/443#event-9832597525).

Solved it, pulled the latest development branch and merged with this branch (#310).

**Comment by atteggiani** [comment]
> Thanks for these changes @atteggiani ! These icons are already looking great to me and are really informative overall on the hive for showing external websites links.
> 
> Just a thought on the `vertical alignment` of the icon - do these icons look better if aligned at the top (as in the current implementation) or could we possibly try vertically centering them?
> 
> Otherwise, I am very happy with the current implementation :)

I tried rendering them vertically centered, but I personally don't like them. To me it gives them a bit too much importance.

**Pull request merged**
